### ISSUE TITLE
Atskirti parametrus (pvz. Facebook API)

### ISSUE THREAD

**Issue by justrau** [nfqakademija/DropTable#4]
https://github.com/nfqakademija/DropTable/blob/master/app/config/config.yml#L82
Siūlau parametrų reikšmes (bent jau Facebook kol kas) dėti į /config/parameters.yml ir dėti jį į .gitignore, nereikės kaskart pafetchinus keitinėti.

**Comment by lukasvtechceo** [comment]
šiaip dėti į gitignore išeitis, bet nelabai sexy, nes iš esmės šis failas reikalingas VCS'e. kita kart galit ir pamirš išimt iš gitignore, kai bus kokie pakeitimai. Bet jei norit daryt su gitignore, tada siulau susikurt dar viena paramsu faila: parameters_fb.yml ir i ji susidet tik kiekvienam unikalius parametrus ir ji isidet i gitignore.  
Bet papraščiausia, tieisog kas kart žiūrėti, kas yra commitinama ir paskui PR'e pasitikrinti. Jei pamatėt, kad PR kažkas negerai, galit ipushinti fix'a, ogit tai matys kaip bendra pakeitimu visuma...
